apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
      - name: from-build-pack
        resources: {}
        taskSpec:
          metadata: {}
          stepTemplate:
            image: uses:jenkins-x/jx3-pipeline-catalog/tasks/typescript/pullrequest.yaml@versionStream
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            workingDir: /workspace/source
          steps:
            - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
              name: ""
              resources: {}
            - env:
              - name: GIT_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: tekton-git
              - name: GIT_USER
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: tekton-git
              image: ghcr.io/jenkins-x/jx-release-version:2.5.1
              name: next-version
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx-release-version --output-format {{.Major}}.{{.Minor}}.{{.Patch}}-rc > VERSION
            - image: ghcr.io/jenkins-x/jx-boot:3.2.216
              name: jx-variables
              resources: {}
              script: |
                #!/usr/bin/env sh
                jx gitops variables
                echo "modify .jx/variables.sh with \"-rc\" values"
                source .jx/variables.sh
                sed -i "s/-rc/-rc.$BUILD_NUMBER/g" .jx/variables.sh
                cat .jx/variables.sh
                jx gitops pr variables
            - image: node:12-slim
              name: npm-version
              resources: {}
              script: |
                #!/usr/bin/env bash
                source .jx/variables.sh
                npm version $VERSION
            - name: build-npm-install
              resources: {}
            - name: build-npm-test
              resources: {}
            - image: node:12-slim
              name: npm-publish
              resources: {}
              script: |
                #!/bin/sh
                npm run build
                npm publish
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
